# 更新我们yum包以及内核
- name: Upgrade yum packages
  become: True
  yum: name=* state=latest
                                               
# 服务器安装我们必须用的软件 git docker
- name: Install yum packages
  become: True
  yum: name={{ item }} update_cache=yes
  with_items:
    - git
    - docker

# 开机启动docker
- name: systemctl enable docker.service
  become: True
  command: systemctl enable docker.service
      
# 添加docker用户组
- name: Make sure we have a 'docker' group, user can join docker group and run docker with non-root
  become: True
  group:
    name: docker
    state: present

# 把我们的操作用户添加入docker组
- name: add docker group to ansible user
  become: True
  user:
   name: ansible
   groups: docker
   append: yes

# 安装docker编排工具docker-compose,开发环境及其我们统一使用docker-compose.沙箱和生产环境使用kubernetes
- name: copy docker-compose 
  become: True
  copy: 
    src: docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    owner: root
    group: root
    mode: "u+x,g+x,o+x"

# 复制docker 服务的配置文件,我们修改了docker存储的路径,添加了docker的私有仓库地址(方便我们更新镜像)
- name: set the docker config file
  become: True
  template:
    src: docker-config.j2
    dest: /etc/sysconfig/docker
  notify: restart docker


                                                                                                         
