# 更新服务器软件包
- name: upgrade all packages
  yum: name=* state=latest
  become: true

# 服务器安装我们必须用的软件
- name: Install yum packages
  become: true
  yum: name={{ item }} update_cache=yes
  with_items:
    - etcd
    - kubernetes-master

# 开机启动服务
- name: systemctl enable services
  become: true
  command: systemctl enable {{ item }}
  with_items:
    - etcd
    - kube-apiserver
    - kube-scheduler
    - kube-controller-manager

# 格式化磁盘
- include: format-disk.yml

# 创建交换分区
- include: swap.yml

# 修改etcd 配置
- include: etcd.yml

# 修改k8s.apiserver 配置
- include: k8s-apiserver.yml

# 修改k8s.controller-manager 配置
- include: k8s-controller-manager.yml

# 修改k8s.scheduler 配置
- include: k8s-scheduler.yml

# 启动服务所有服务
- name: start all services
  service: name={{ item }} state=started
  become: true
  with_items:
    - etcd
    - kube-apiserver
    - kube-scheduler
    - kube-controller-manager


# 定义flannel 网络配置
- include: flannel.yml
