# 更新服务器软件包
- name: upgrade all packages
  yum: name=* state=latest
  become: true

# 复制docker-engine的源
- copy: src=docker.repo dest=/etc/yum.repos.d/docker.repo owner=root group=root mode=0655
  become: true
    
# 服务器安装我们必须用的软件
- name: install yum packages
  become: true
  yum: name={{ item }} update_cache=yes 
  with_items:
    - docker 
    - flannel

# 格式化硬盘
- include: format-disk.yml

# 创建交换分区
- include: swap.yml

# docker 使用direct-lvm代替loopback
#- include: docker-rect-lvm.yml

# 修改flannel 配置,因为flannel的脚本会再flannel服务启动时候关闭docker0网管,所以要再docker运行前运行
- include: flannel.yml

# 修改docker配置
- include: docker.yml

# 修改k8s.kubelet 配置
- include: k8s-kubelet.yml

# 修改k8s.kube-proxy 配置
- include: k8s-kube-proxy.yml

# 修改k8s的路由bug
- name: fix k8s bug 
  command: ip route add "{{ service_cluster_ip_range }}" dev docker0
  become: true
