# 更新服务器软件包
- name: upgrade all packages
  yum: name=* state=latest
  become: true

# 服务器安装我们必须用的软件
- name: install yum packages
  become: true
  yum: name={{ item }} update_cache=yes 
  with_items:
    - docker  
    - kubernetes-node
    - flannel

# 开机启动服务
- name: systemctl enable services
  become: true
  command: systemctl enable {{ item }}
  with_items:
    - flanneld
    - kubelet
    - kube-proxy

# 格式化硬盘
- include: format-disk.yml

# 创建交换分区
- include: swap.yml

# docker 使用direct-lvm代替loopback
- include: docker-direct-lvm.yml

# 修改docker配置
- include: docker.yml

# 修改k8s.kubelet 配置
- include: k8s-kubelet.yml

# 修改k8s.kube-proxy 配置
- include: k8s-kube-proxy.yml

# 修改flannel 配置
- include: flannel.yml

# 启动服务所有服务
- name: start all services
  become: true
  service: name={{ item }} state=started 
  with_items:
    - flanneld
    - docker
    - kubelet
    - kube-proxy
