# 下载搭建rancher镜像
- name: pull an image
  command: docker pull rancher/server:v1.6.5

#- name: rancher/server
#  docker_container:
#    name: rancher-server
#    image: rancher/server
#    state: started
#    recreate: yes
#    restart_policy: always
#    ports:
#    - "8080:8080"
#    volumes:
#   - "/data/mysql:/var/lib/mysql"

#- name: wait for the Rancher server to start
#  action: command docker logs {{ rancher_name }}
#  register: rancher_logs
#  until: rancher_logs.stdout.find("Listening on") != -1
#  retries: 30
#  delay: 10

#- name: print Rancher's URL
#  debug: msg="You can connect to rancher server http://{{ ansible_default_ipv4.address }}:{{ rancher_port }}"
