- name: check if pam_pwquality.so exist in password-auth
  shell: /usr/bin/cat /etc/pam.d/passwd | grep "pam_pwquality.so"
  register: pam_pwquality_exist_in_passwd
  failed_when: "pam_pwquality_exist_in_passwd.rc != 0 and pam_pwquality_exist_in_passwd.rc != 1"  
  changed_when: false

- name: update pam_pwquality.so in type account
  pamd:
    name: passwd
    type: password
    control: required
    module_path: pam_pwquality.so
    module_arguments: 'retry=3'
    state: updated
  when: pam_pwquality_exist_in_passwd.rc == 0

- name: insert pam_pwquality.so in type account
  shell: echo "password  required  pam_pwquality.so retry=3" >> /etc/pam.d/passwd
  when: pam_pwquality_exist_in_passwd.rc == 1

- name: sync pwquality.conf
  copy: 
    src: files/pwquality.conf
    dest: /etc/security/pwquality.conf
    owner: root
    group: root
    mode: 0644
