# 修改hostname
- include: hostname.yml

# install packages 
- name: install required packages
  yum: name={{item}} state=latest
  with_items:
    - lvm2
    - yum-utils
    - device-mapper-persistent-data

# 关闭selinux
- name: close selinux
  selinux: state=disabled

# 格式化docker 精简池
- include: format-docker-disk.yml

# 格式化数据盘
- include: format-data-disk.yml

# 创建交换分区
- include: swap.yml
