  - name: RancherOS rancher/agent
    docker:
      name: rancheragent
      image: rancher/agent
      privileged: True
      state: reloaded
      restart_policy: always
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      command: "{{ url_contents }}"
      env:
        CATTLE_AGENT_IP: "{{ ip_contents }}"
        CATTLE_HOST_LABELS: "{{ labels_contents }}"